version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./temp_uploads:/app/temp_uploads
    environment:
      - FLASK_ENV=production
    restart: unless-stopped 
